### ISSUE TITLE
Current release causing deprecation error from `os.tmpDir`

### ISSUE THREAD

**Issue by willyb321** [feross/fs-chunk-store#10]
[This line](https://github.com/feross/fs-chunk-store/blob/v1.6.4/index.js#L17).  
I am using webtorrent in my electron app, and getting an error because of it.  
It seems to have been fixed in the current HEAD, but not in npm version.

**Comment by feross** [comment]
1.6.5

**Comment by willyb321** [comment]
Thanks!
