### ISSUE TITLE
Cannot create folder that already exists.

### ISSUE THREAD

**Issue by gdborton** [feross/fs-chunk-store#13]
I'm getting an `eexists` error when trying something similar to the below code, telling me the outputPath already exists:

```js
const torrent = client.add(torrent, { path: outputPath });
torrent.on('done', () => {
  const readStream = torrent.files[fileIndex].createReadStream();
  fluent(readStream);
});
```

From what I can see on my filesystem, webtorrent has created the folder and added a single file to it, then errors when I later try to create a readstream from it.  I was able to edit the copy of fs-chunk-store in my local node_modules folder, and reverting this change fixes the problem for me:

https://github.com/feross/fs-chunk-store/commit/802dfa926688d23632bc4f4579c27edfa74042ea

Node's docs say that `{ recursive: true }` prevents `EEXISTS` errors, but maybe that doesn't count for the child most folder?

**Comment by feross** [comment]
This shouldn't happen. Perhaps this was a Node.js bug. What version of Node.js were you using?

Since this issue is old, I'm pre-emptively going to close it but please feel free to reply and I'll re-open if this is still an issue.
